# Generated by Django 5.2 on 2025-05-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('file', 'folder')},
        ),
    ]
