# Generated by Django 5.2 on 2025-05-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_alter_file_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='file',
            name='full_path',
            field=models.TextField(db_index=True, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='full_path',
            field=models.TextField(db_index=True, editable=False, unique=True),
        ),
    ]
