# Generated by Django 3.2.19 on 2025-05-06 07:16

from django.db import migrations
from django.conf import settings

def populate_file_folder_owners(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    File = apps.get_model('file', 'File')
    Folder = apps.get_model('file', 'Folder')
    db_alias = schema_editor.connection.alias

    # --- Assign a default owner (e.g., user with ID 1) ---
    # !!! IMPORTANT: Change this logic if you need a different default owner !!!
    try:
        default_user = User.objects.using(db_alias).get(pk=1)
    except User.DoesNotExist:
        # Handle case where user 1 doesn't exist - maybe create one or raise an error?
        # For now, we'll skip the update if the user isn't found.
        print("\nWarning: Default user with ID 1 not found. Skipping owner population.")
        return

    # Populate owner for Files without one
    files_updated = File.objects.using(db_alias).filter(owner__isnull=True).update(owner=default_user)
    if files_updated:
        print(f"\nUpdated owner for {files_updated} File objects.")

    # Populate owner for Folders without one
    # Ensure we don't try to update the conceptual root folder placeholder if it was created before owner existed
    folders_updated = Folder.objects.using(db_alias).filter(owner__isnull=True).exclude(full_path__startswith='/userroot_').update(owner=default_user)
    if folders_updated:
        print(f"\nUpdated owner for {folders_updated} Folder objects.")

    # Handle conceptual root folders separately (if they exist without an owner)
    root_folders_updated = Folder.objects.using(db_alias).filter(owner__isnull=True, name__isnull=True, parent__isnull=True).update(owner=default_user)
    if root_folders_updated:
         print(f"\nUpdated owner for {root_folders_updated} root Folder objects.")


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0005_auto_20250506_0715'),
    ]

    operations = [
        migrations.RunPython(populate_file_folder_owners),
    ]
