# Generated by Django 5.2 on 2026-03-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0006_alter_mailbox_options_mailbox_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='imap_uid',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['mailbox', 'imap_uid'], name='email_mailbox_uid_idx'),
        ),
    ]
