# Generated by Django 5.2 on 2026-02-26 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0009_apptoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharedFolderMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('read', 'Read only'), ('write', 'Read & Write'), ('admin', 'Admin')], default='read', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='folder',
            name='unique_root_folder_per_user',
        ),
        migrations.AlterField(
            model_name='file',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='folder',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', True), ('owner__isnull', False), ('parent__isnull', True)), fields=('owner',), name='unique_root_folder_per_user'),
        ),
        migrations.AddField(
            model_name='sharedfolder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shared_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedfolder',
            name='root_folder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_folder_ref', to='file.folder'),
        ),
        migrations.AddField(
            model_name='sharedfoldermembership',
            name='shared_folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='file.sharedfolder'),
        ),
        migrations.AddField(
            model_name='sharedfoldermembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_folder_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sharedfoldermembership',
            unique_together={('shared_folder', 'user')},
        ),
    ]
