# Generated by Django 5.2 on 2026-03-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0010_contactfolder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
    ]
