# Generated by Django 5.2 on 2026-03-22 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0011_add_allowed_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutOfOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('subject', models.CharField(default='Out of office', max_length=255)),
                ('body', models.TextField(blank=True, default='I am currently out of the office and will reply when I return.')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='out_of_office', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutOfOfficeReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(max_length=500)),
                ('replied_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ooo_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'sender_email')},
            },
        ),
    ]
